getwd()
setwd("C:/Users/Lohith/Documents")
data1 = read.csv("Telecom_Data.csv")
View(data1)
data1 = data1 [-c(4)]
data1$churn = as.factor(data1$churn)
library("caTools")
sample = sample.split(data1$churn,SplitRatio = 0.70)
train = subset (data1,sample==TRUE)
test = subset (data1,sample==FALSE)
install.packages("randomForest")
library("randomForest")
model = randomForest(churn~.,data=train)
test$Predicted = predict(model,test)
View(test)
table(test$churn,test$Predicted)
varImpPlot(model)
